#!/usr/bin/env python3
"""
Read a contact-list and record frequencies of residue interactions. If --output
is defined write the results to a file, otherwise write to stdout.
"""

import argparse as ap
from collections import defaultdict
import sys
import re


def main():
    parser = ap.ArgumentParser(description=__doc__, formatter_class=ap.RawTextHelpFormatter)
    parser.add_argument('--input',
                        type=ap.FileType("r"),
                        required=True,
                        help='Contact-list generated by MDContactNetwork')

    parser.add_argument('--output',
                        type=ap.FileType("w"),
                        required=False,
                        help='Residue contact frequencies')

    args = parser.parse_args()

    interaction_frames = defaultdict(set)
    max_frame = 0
    total_frames = 0
    for line in args.input.readlines():
        line = line.strip()
        if not line:  # Ignore empty lines
            continue

        # Parse header
        if line[0] == "#":
            total_frame_match = re.search(r'total_frames:(\d+)', line)
            if total_frame_match:
                total_frames = int(total_frame_match.group(1))
            continue

        # Regex that matches a contact line and groups the frame number and the two first residues,
        frame_resi_match = re.match(r'^(\d+)\t.*?\t([^:]+:[^:]+:\d+).*?\t([^:]+:[^:]+:\d+)', line)
        frame = int(frame_resi_match.group(1))
        res1 = frame_resi_match.group(2)
        res2 = frame_resi_match.group(3)

        if res2 < res1:
            res1, res2 = res2, res1

        interaction_frames[(res1, res2)].add(frame)
        if frame > max_frame:
            max_frame = frame

    if total_frames == 0:
        print("total_frames must be larger than zero and defined in header")
        exit(-1)

    assert max_frame < total_frames

    # Define output channel
    if args.output:
        output = args.output
    else:
        output = sys.stdout

    # Write contacts
    for (res1, res2), frames in interaction_frames.items():
        frequency = len(frames) / float(max_frame + 1)
        output.write("\t".join((res1, res2, str(frequency))) + "\n")

    if args.output:
        args.output.close()


if __name__ == "__main__":
    main()