#!/usr/bin/env python3
"""
Read a contact-list and record frequencies of residue interactions
"""

import argparse as ap
from collections import defaultdict
import re


def main():
    parser = ap.ArgumentParser(description=__doc__, formatter_class=ap.RawTextHelpFormatter)
    parser.add_argument('--input',
                        type=ap.FileType("r"),
                        required=True,
                        help='Contact-list generated by MDContactNetwork')

    parser.add_argument('--output',
                        type=ap.FileType("w"),
                        required=True,
                        help='List of residue frequencies')

    args = parser.parse_args()

    interaction_frames = defaultdict(set)
    max_frame = 0
    for line in args.input.readlines():
        if not line:  # Ignore empty lines
            continue

        frame_resi_match = re.match(r'^(\d+)\t.*?\t([^:]+:[^:]+:\d+).*?\t([^:]+:[^:]+:\d+).*', line)
        frame = int(frame_resi_match.group(1))
        res1 = frame_resi_match.group(2)
        res2 = frame_resi_match.group(3)

        if res2 < res1:
            res1, res2 = res2, res1

        interaction_frames[(res1, res2)].add(frame)
        if frame > max_frame:
            max_frame = frame

    for (res1, res2), frames in interaction_frames.items():
        frequency = len(frames) / float(max_frame + 1)
        args.output.write("\t".join((res1, res2, str(frequency))) + "\n")

    args.output.close()


if __name__ == "__main__":
    main()